export RDS_SECRET='rds!db-809e49e3-4593-434e-98ad-7f75b048a08f'
export POSTGRES_URL="direct-access-test-db.ckvrhv4h8wm8.ap-south-1.rds.amazonaws.com:6543"
export AUTOCRM_APP_ENTERPRISE_ID=autocrm 
export AUTOCRM_ADMIN_ID="ananth+autocrm@iamdave.ai"
export AUTOCRM_ADMIN_PHONE_NUMBER=99980838165
export AUTOCRM_ADMIN_PASSWORD="Aut0C4M@Gr^d"
export AWS_ACCESS_KEY_ID="<your aws access key>"
export AWS_SECRET_ACCESS_KEY="<your aws secret key>"
export AWS_DEFAULT_REGION="ap-south-1"
export GOOGLE_APPLICATION_CREDENTIALS="/your/path/to/firebase_secrets.json"
