export ENVIRONMENT=local
export AUTH_HOST_USER_ID=<YOUR_USER_ID>
export AUTH_HOST=<YOUR_AUTH_HOST>
export AUTH_HOST_API=<YOUR_API_KEY>
export AUTH_HOST_ENTERPRISE_ID=<YOUR_ENTERPRISE_ID>
worker -m tasks.py -n 8