FROM ubuntu:22.04
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update -yy
RUN apt install software-properties-common zip unzip python3-pip redis-tools libpq-dev curl jq -yy
RUN apt-get install ffmpeg -yy
RUN update-alternatives --install /usr/bin/python python /usr/bin/python3 10

WORKDIR /root/
COPY <zipname>.zip /root/
RUN unzip <zipname>.zip -d app/
WORKDIR /root/app/
COPY credentials.json ./

RUN pip install -U pip setuptools
RUN pip install --ignore-installed -r requirements.txt
CMD [ "bash" , "./start_process_container.sh" ]
