"""
Meta Conversions API — HTTP Client
=====================================
Handles authentication, rate-limiting, retries and sending
events to Meta's Graph API endpoint.

Endpoint format:
  POST https://graph.facebook.com/{API_VERSION}/{PIXEL_ID}/events
       ?access_token={ACCESS_TOKEN}

Rate limits (Meta documentation):
  - Standard tier: 10 000 events / 10 minutes per Pixel
  - Batch events together (up to 1 000 events per API call) to stay well
    within limits.
  - On HTTP 429 / "API Too Many Calls" error code 80004, back off with
    exponential jitter before retrying.

Authentication:
  - Uses a System User Access Token generated from Business Manager /
    Events Manager → CRM Integration guide → "Generate Access Token".
  - Tokens are long-lived when generated by System Users; rotate them
    per your security policy.

References:
  https://developers.facebook.com/documentation/ads-commerce/conversions-api/using-the-api#send
  https://developers.facebook.com/documentation/ads-commerce/conversions-api/conversion-leads-integration/crm-integration/3-implementing-the-crm-integration#step-2-create-an-access-token-and-an-api-call
"""

import os
import time
import logging
import requests
from typing import Optional

logger = logging.getLogger(__name__)

# ─────────────────────────────────────────────────────────────────────────────
# Constants
# ─────────────────────────────────────────────────────────────────────────────

GRAPH_API_VERSION = "v21.0"  # Update before the Marketing API expiry date
GRAPH_BASE_URL = "https://graph.facebook.com"
MAX_EVENTS_PER_CALL = 1_000   # Meta hard limit per single POST
MAX_RETRIES = 3
BASE_BACKOFF_SECONDS = 2      # Exponential: 2, 4, 8 seconds


class MetaCAPIError(Exception):
    """Raised when Meta CAPI returns a non-retryable error."""
    def __init__(self, message: str, status_code: int = 0, fb_error: dict = None):
        super().__init__(message)
        self.status_code = status_code
        self.fb_error = fb_error or {}


class MetaCAPIRateLimitError(MetaCAPIError):
    """Raised on HTTP 429 / FB error code 80004 (Too Many Calls)."""


# ─────────────────────────────────────────────────────────────────────────────
# Client
# ─────────────────────────────────────────────────────────────────────────────

class MetaCAPIClient:
    """
    Thread-safe client for sending Conversion Lead events to Meta CAPI.

    Usage:
        client = MetaCAPIClient.from_env()
        result = client.send_events([event_dict, ...])

    Environment variables (set in local.sh or secrets manager):
        META_PIXEL_ID          : Your CRM Pixel ID from Events Manager.
        META_CAPI_ACCESS_TOKEN : System User access token.
        META_CAPI_TEST_CODE    : (Optional) Test event code for sandbox testing.
    """

    def __init__(
        self,
        pixel_id: str,
        access_token: str,
        api_version: str = GRAPH_API_VERSION,
        test_event_code: Optional[str] = None,
    ):
        """
        Args:
            pixel_id         : Meta Pixel ID (from Events Manager).
            access_token     : System User access token.
            api_version      : Graph API version string, e.g. "v21.0".
            test_event_code  : Optional test code — events will only appear
                               in Test Events tab and NOT affect live data.
        """
        if not pixel_id:
            raise ValueError("MetaCAPIClient: pixel_id is required.")
        if not access_token:
            raise ValueError("MetaCAPIClient: access_token is required.")

        self.pixel_id = pixel_id
        self.access_token = access_token
        self.api_version = api_version
        self.test_event_code = test_event_code
        self._endpoint = (
            f"{GRAPH_BASE_URL}/{api_version}/{pixel_id}/events"
        )

    # ── Factory ────────────────────────────────────────────────────────────────

    @classmethod
    def from_env(cls) -> "MetaCAPIClient":
        """
        Instantiate from environment variables.

        Required:
            META_PIXEL_ID
            META_CAPI_ACCESS_TOKEN

        Optional:
            META_CAPI_API_VERSION   (default: v21.0)
            META_CAPI_TEST_CODE     (sandbox testing only)
        """
        pixel_id = os.environ.get("META_PIXEL_ID", "")
        access_token = os.environ.get("META_CAPI_ACCESS_TOKEN", "")
        api_version = os.environ.get("META_CAPI_API_VERSION", GRAPH_API_VERSION)
        test_code = os.environ.get("META_CAPI_TEST_CODE", None)

        return cls(
            pixel_id=pixel_id,
            access_token=access_token,
            api_version=api_version,
            test_event_code=test_code,
        )

    # ── Public API ─────────────────────────────────────────────────────────────

    def send_events(self, events: list, test_event_code: Optional[str] = None) -> dict:
        """
        Send one or more Conversion Lead events to Meta CAPI.

        Automatically batches if len(events) > MAX_EVENTS_PER_CALL.
        Retries up to MAX_RETRIES times with exponential back-off on rate limit.

        Args:
            events         : List of event dicts from build_lead_event_payload().
            test_event_code: Override instance-level test code for this call.

        Returns:
            dict: Last successful API response body (contains "events_received").

        Raises:
            MetaCAPIError          : Non-retryable error from Meta.
            MetaCAPIRateLimitError : Persistent rate limit despite retries.
        """
        effective_test_code = test_event_code or self.test_event_code

        # Chunk into batches of MAX_EVENTS_PER_CALL
        all_responses = []
        for i in range(0, max(len(events), 1), MAX_EVENTS_PER_CALL):
            batch = events[i: i + MAX_EVENTS_PER_CALL]
            resp = self._post_with_retry(batch, effective_test_code)
            all_responses.append(resp)
            logger.info(
                "MetaCAPI: batch %d sent — %d events received by Meta.",
                i // MAX_EVENTS_PER_CALL + 1,
                resp.get("events_received", 0),
            )

        return all_responses[-1] if all_responses else {}

    def send_single_event(self, event: dict, test_event_code: Optional[str] = None) -> dict:
        """Convenience wrapper to send a single event dict."""
        return self.send_events([event], test_event_code=test_event_code)

    # ── Internal ───────────────────────────────────────────────────────────────

    def _build_payload(self, events: list, test_event_code: Optional[str] = None) -> dict:
        payload = {"data": events}
        if test_event_code:
            payload["test_event_code"] = test_event_code
        return payload

    def _post_with_retry(self, events: list, test_event_code: Optional[str]) -> dict:
        """
        POST a batch with exponential-backoff retry on rate-limit responses.
        """
        payload = self._build_payload(events, test_event_code)
        params = {"access_token": self.access_token}

        for attempt in range(1, MAX_RETRIES + 1):
            try:
                response = requests.post(
                    self._endpoint,
                    params=params,
                    json=payload,
                    timeout=30,
                )
            except requests.exceptions.RequestException as exc:
                if attempt >= MAX_RETRIES:
                    raise MetaCAPIError(
                        f"Network error sending to Meta CAPI after {attempt} attempts: {exc}"
                    ) from exc
                wait = BASE_BACKOFF_SECONDS ** attempt
                logger.warning(
                    "MetaCAPI: Network error on attempt %d/%d — retrying in %ds. %s",
                    attempt, MAX_RETRIES, wait, exc,
                )
                time.sleep(wait)
                continue

            # ── Parse response ─────────────────────────────────────────────
            if response.status_code == 200:
                return response.json()

            try:
                body = response.json()
                fb_error = body.get("error", {})
                error_code = fb_error.get("code", 0)
                error_msg = fb_error.get("message", response.text)
            except Exception:
                fb_error = {}
                error_code = 0
                error_msg = response.text

            # Rate limit: HTTP 429 or FB error code 80004
            is_rate_limit = (
                response.status_code == 429
                or error_code == 80004
            )

            if is_rate_limit and attempt < MAX_RETRIES:
                wait = BASE_BACKOFF_SECONDS ** attempt
                logger.warning(
                    "MetaCAPI: Rate limit hit (attempt %d/%d) — backing off %ds.",
                    attempt, MAX_RETRIES, wait,
                )
                time.sleep(wait)
                continue

            if is_rate_limit:
                raise MetaCAPIRateLimitError(
                    f"Meta CAPI rate limit exceeded after {MAX_RETRIES} retries.",
                    status_code=response.status_code,
                    fb_error=fb_error,
                )

            # Any other non-200 is a hard failure
            raise MetaCAPIError(
                f"Meta CAPI error {response.status_code}: {error_msg}",
                status_code=response.status_code,
                fb_error=fb_error,
            )

        # Should not reach here
        raise MetaCAPIError("MetaCAPI: Exhausted retries without success.")
