[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "autobot-voice"
description = "Voice App package for Autobot Agents"
readme = "README.md"
requires-python = ">=3.8"
license = "MIT"
version = "0.0.0"

authors = [
  { name = "DaveAI", email = "nikit@iamdave.ai" }
]

# mark fields read dynamically
dynamic = [ "dependencies"]

classifiers = [
  "Programming Language :: Python :: 3",
  "Operating System :: OS Independent"
]

[project.urls]
Homepage = "https://git@bitbucket.org:SocioGraph/autobot_agents.git"
Source = "https://git@bitbucket.org:SocioGraph/autobot_agents.git"
Issues = "https://git@bitbucket.org:SocioGraph/autobot_agents.git/issues"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
exclude = ["tests", "tests.*"]

[tool.setuptools.dynamic]
dependencies = { file = ["requirements.txt"] }
