import json
import os
from ai_service import ai_service_app
import re
try:
    from .base_agent import BaseAgent, gryd
except ImportError:
    from base_agent import BaseAgent, gryd



class TemplateCreatorAgent(BaseAgent):
    """
    Generates WhatsApp template_name, template_message and buttons
    using structured CRM + prompt metadata.
    """

    def __init__(self, source=None):
        super().__init__(source=source)
        self.source = source or {}
        self.model_identifier = "gcp-gemini-2.5-flash-lite"

    def run(self):
        ai_prompt = self._build_prompt(self.source)
        ai_response = ai_service_app.get_llm_response(
                messages=ai_prompt,
                model_identifier=self.model_identifier
            )

        parsed = self._parse_ai_response(ai_response)
        final = self._assemble_output(self.source, parsed)
        return final

    def _build_prompt(self, data : dict):
        """
        Constructs the AI prompt based on the pre-defined schema.

        """
        language = data.get("languages",["English"])[0]

        master_prompt = f"""
          "prompt_name": "Autobot WhatsApp Template Generator v2",
          "version": "2.0",
          "author": "DaveAI Prompt Engineering Team", 
          "description": "Schema-driven WhatsApp template generation prompt for automotive BDC automation. Uses CRM attributes to generate contextual WhatsApp message templates without explicit journey state.",
          "role": "You are an automotive sales and BDC communication specialist. You craft personalized WhatsApp message templates for car dealerships using structured CRM data.",
          "objective": This is the campaign objective and the template should be according to this : {json.dumps(data.get("campaign_objective",""))},
          "language" : These are the languages, default is english but if there are more languages then you'll be generating the template in the language : {language}
          "input data": These are the variables {json.dumps(data.get("data",{}))}" This data contains the attributes and the description of the attribute, You'll be using it to write the body message.",
          "campaign_type" : {json.dumps(data.get("campaign_type",""))}
          "generation_rules": [
            "Interpret the context using lead_source, campaign_type, objective, and previous_interaction_details.",
            "Determine tone and message goal from sentiment_score, user_remark, and emotions.",
            "Use 2-4 attributes for personalization; do not overpopulate." The ,
            "Craft the message to be under 400 characters, formatted for WhatsApp readability.",
            "Avoid yes/no questions and hyperlinks.",
            "Always end with a motivating close and include 2-3 CTAs from the approved list."
          ],
          "cta_library": [
            "Download Brochure",
            "Compare Variants",
            "Compare with Other Brands",
            "Book a Test Drive",
            "Book a Showroom Visit",
            "Locate a Showroom",
            "Request a Call Back",
            "Confirm Booking",
            "Exchange Old Car"
          ] 
          - If there might some previously generated cta buttons. 
          -  You'll get those previously generated cta buttons here in this list : {json.dumps(data.get("cta_buttons",[]))} Just directly put these in the "suggested_ctas" without changeing anything. They maynot be in the cta_library, don't worry for that. Just put them directly.
          - If cta buttons are/is already there in the input, Do not generate/add a new one. Only return those.
          - If the list is empty then you'll retuen 2-3 relevant ctas in "suggested_ctas" according to the relevancy of the overall template but "Request a Call Back" will be always there in the list.
        """


        user_prompt = """
        You are a WhatsApp template generator agent. Check the system_prompt for your task. Its just a template

        Example I am giving you: Do not generate the same one
        example input  : data = {
                "person_name": "string",
                "model_preference" : "string",
                "dealer_name":"string",
                "brand_perception": "string"...
        } you'll get many more attributes and description, Just use the relevant ones to generate the template. 
         
        "output_format": {
            "template_name": "string",
            "template_text": "string",
            "attributes_used": ["string"],
            "suggested_ctas": ["string"],
          } Do not change the attribute names.

        "example_output": {
            "template_name": "Autogenerated WhatsApp Template",
            "template_text": "Hi {{person_name}}, thanks for exploring the {{model_preference}}! Our team at {{dealer_name}} has curated variant and offer details to help you choose the right fit. Let’s take the next step together.",
            "attributes_used": ["person_name", "model_preference", "dealer_name"],
            "suggested_ctas": ["Book a Test Drive", "Compare Variants", "Schedule a Call Back"]
          } This example_output is just an example, don't generate the exact one, Just consider this as an example only. The inputs are there in the system prompt as "input_schema/CRM Data/ input data" and other things are also there for your reference. Take and create a new one according to the data. Never return everything inside just template_message, Use the example_output properly. template_name will be related to campaign objective and campaign type.

        """


        return [{"role": "system", "content": master_prompt},
                {"role": "user", "content": user_prompt}]

    def _parse_ai_response(self, text):
        try:
            # Try to parse directly first
            return json.loads(text)
        except json.JSONDecodeError:
            try:
                # Extract JSON from markdown code blocks
                json_match = re.search(r'```(?:json)?\s*(.*?)\s*```', text, re.DOTALL)
                if json_match:
                    json_str = json_match.group(1)
                    return json.loads(json_str)
                else:
                    # Try to find JSON object in the text
                    json_match = re.search(r'\{.*\}', text, re.DOTALL)
                    if json_match:
                        return json.loads(json_match.group(0))
                    else:
                        raise ValueError("No JSON found in response")
            except Exception as e:
                print(f"Failed to parse AI response: {e}")
                print(f"Raw response: {text}")
                # Fallback to basic structure
                return {
                    "template_name": "Auto_Generated_Template",
                    "template_text": "Thank you for your interest. Please contact us for more information.",
                    "suggested_ctas": ["Request a Call Back"]
                }


    def _assemble_output(self, source, generated):
        buttons = []
        template_button_payloads = []

        template_name = (
            generated.get("template_name", "").lower().strip().replace(" ", "_").replace("-", "_")
        )

        suggested_ctas = generated.get("suggested_ctas", [])

        # Override buttons if source has custom CTA list
        if "cta_buttons" in source and isinstance(source["cta_buttons"], list):
            buttons = [
                {"type": "QUICK_REPLY", "text": cta}
                for cta in source["cta_buttons"]
            ]
            for cta in source["cta_buttons"]:
                slug = cta.lower().strip().replace(" ", "_").replace("-", "_")
                template_button_payloads.append(f"{template_name}-{slug}")
        else:
            buttons = [
                {"type": "QUICK_REPLY", "text": cta}
                for cta in suggested_ctas
            ]
            for cta in suggested_ctas:
                slug = cta.lower().strip().replace(" ", "_").replace("-", "_")
                template_button_payloads.append(f"{template_name}-{slug}")

        return {
            "template_name": generated.get("template_name"),
            "template_message": generated.get("template_text"),
            "buttons": buttons,
            "template_button_payloads": template_button_payloads
        }

AUTOCRM_APP_ENTERPRISE_ID = os.environ.get("AUTOCRM_APP_ENTERPRISE_ID", "autocrm")

# @gryd.is_a_task('generate_whatsapp_template',logger_param='logger',job_param='job')
# def generate_whatsapp_template(user_data=None, logger=None, job=None):
#     """
#     Gryd task wrapper for template generation.
#     Matches the structure of your existing worker patterns.
#     """

#     logger = logger or gryd.hp.get_logger(__name__)
#     logger.info("Generating WhatsApp template using CRM data...")

#     user_data = user_data or {}

#     # Instantiate agent
#     agent = TemplateCreatorAgent(source=user_data)

#     # Generate output
#     result = agent.run()

#     logger.info(f"Template generation completed: {result}")

#     # posting logic, if needed later
#     dim = gryd.base_model.Model('template', AUTOCRM_APP_ENTERPRISE_ID)
#     dim.post(result)

#     return result

@gryd.is_a_task('generate_whatsapp_template', logger_param='logger', job_param='job')
def generate_whatsapp_template(user_data=None, logger=None, job=None):
    logger = logger or gryd.hp.get_logger(__name__)
    logger.info("Creating WhatsApp template using CRM data...")

    try:
        user_data = user_data or {}
        logger.info(f"Incoming CRM data: {user_data}")
        
        # Instantiate TemplateCreatorAgent
        agent = TemplateCreatorAgent(source=user_data)
        logger.info("Running template generation agent...")

        result = agent.run()

        logger.info(f"Template generated successfully: {result}")

        # Post to database only if enterprise_id exists
        try:
            dim = gryd.base_model.Model('templates', AUTOCRM_APP_ENTERPRISE_ID)
            logger.info(f"Posting result to model 'templates' under enterprise '{AUTOCRM_APP_ENTERPRISE_ID}'")

            dim.post(result)

            logger.info("Post completed successfully!")
        except Exception as db_error:
            logger.info(f"Failed posting to Gryd model: {db_error}")

        return result

    except Exception as e:
        logger.info(f"WhatsApp template generation failed: {str(e)}")
        raise

